# -*- coding: utf-8 -*-
"""Recomends_ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h1gG860UN6g8pc2q3AvPFzVNwRjD6Z12
"""

import pandas as pd
import numpy as np
#import surprise
#import apyori
import statistics as st

! pip install surprise
! pip install apyori

def func_converse(value):
  return (np.median(value)+np.mean(value))/2

conversion_high={
    'high': 'max',
    'close': 'mean',
    'open': 'median',
    'vol': func_converse,


    'low': 'min'
   #


}

data=pd.read_csv("/content/EURUSD_1.csv")
print(data.head(20))
print("\n")
data['ts']=pd.to_datetime(data.ts)
data=data.set_index('ts')
#print(data.head(10))

downsampled=data.resample('8H').apply(conversion_high)
#data
#2017-01-02 16:00:00
#2017-01-04 00:00:00
#downsampled.head(50)
#downsampled[]

df=data.iloc[:893]
print(df)
downsampled=df.resample('10s').apply(conversion_high)
downsampled.head(50)

#s=downsampled.loc[downsampled['open'].isna()]
s=downsampled['open'].isna()
s.sum()
#s.pd.Series.interpolate(method='linear' , axis=0 , limit=4508)
#s = pd.Series([0, 2, np.nan, 5])
downsampled.interpolate(method='nearest')

downsampled.interpolate(method='nearest')
np.mean(downsampled['close'])

df = data.copy()
df = df[(df.ts >= '2017-01-05 12:00:00') & (df.ts <= '2017-01-05 13:00:00')]
df['unixtime'] = df.ts.astype(np.int64)

fig = go.Figure(data  = [go.Candlestick(
            x=df['ts'],
            open  = df['open'],
            high  = df['high'],
            low   = df['low'],
            close = df['close']
        )])

fig.show()

df.head()